# Generated by Django 6.1.1 on 2026-10-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Biotech Vintae Pharma Ltd.', max_length=150)),
                ('office_address', models.TextField(default='Jannatul Mawa G/125 Ground Floor, Beside Khaddo Bhaban, Shahid Abdul Jobbar Sarak, Rahman Nagar, Bogura')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('MD', 'Managing Director'), ('FINANCE', 'Finance Director')], max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
