# Generated by Django 6.1.1 on 2026-10-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='Dietary & Nutritional Supplement', max_length=100)),
                ('short_description', models.TextField()),
                ('dosage_instructions', models.CharField(default='1 or 2 tablet daily or as directed by health expert', max_length=200)),
                ('presentation', models.CharField(default='3x10 Tablets per monopack', max_length=100)),
                ('route_of_admin', models.CharField(default='Oral', max_length=50)),
                ('storage_conditions', models.TextField(default='Store in a cool & dry place. Protect from direct sunlight, heat & moisture. Keep out of reach of children.')),
                ('precautions', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(default='Generally well tolerated. Rarely constipation, stomach ache, loss of appetite.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='products.product')),
            ],
        ),
    ]
