# Generated by Django 6.1.1 on 2026-10-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precautions',
            new_name='contraindications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dosage_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='route_of_admin',
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_administration',
            field=models.TextField(blank=True, default='', help_text='e.g. 2 to 4 capsules daily or as advised by physician.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacology_how_it_works',
            field=models.TextField(blank=True, null=True, verbose_name='Pharmacology / How It Works'),
        ),
        migrations.AddField(
            model_name='product',
            name='route_of_administration',
            field=models.CharField(default='Oral', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='therapeutic_class',
            field=models.CharField(blank=True, help_text='e.g. Superfood / Nutritional Supplement', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Herbal and Nutraceuticals', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, default='', help_text='e.g. Capsules in blister pack', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Summary description for cards and listings.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(default='Store in a cool and dry place away from direct sunlight. Keep out of reach of children.', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductCompositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='e.g. Vitamins, Minerals, Antioxidants & Pigments', max_length=150)),
                ('name', models.CharField(help_text='e.g. Vitamin A (as beta-carotene) or Zinc, Magnesium, Calcium', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_rel', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. Treatment and prevention of malnutrition', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications_rel', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Indication',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
